#!/usr/bin/env bash
#/bin/sh

echo "php-cs-fixer & phpstan pre commit hook start"

FILES=`git diff --cached --name-only --diff-filter=ACM | grep -e '.php$'`
if [ -z "$FILES" ]
then
    echo "No php files found in commit."
else
    echo "composer php-cs-fixer-check"
    MSYS_NO_PATHCONV=1 docker-compose run -T --rm php /usr/bin/composer php-cs-fixer-check ${FILES}
    if [ $? -ne 0 ];
    then
      echo "Failed php-cs-fixer check"
      exit 1
    fi
fi

# ignore tests and database folders from phpstan checks
FILES=`git diff --cached --name-only --diff-filter=ACM | grep -e '.php$' | sed -e '/^tests/d' | tr '\n' ' '`
if [ -z "$FILES" ]
then
    echo "No php files to check against phpstan."
else
    echo "composer phpstan-check"
    MSYS_NO_PATHCONV=1 docker-compose run -T --rm php /usr/bin/composer phpstan-check ${FILES}
    if [ $? -ne 0 ];
    then
      echo "Failed phpstan check"
      exit 1
    fi
fi

echo "php-cs-fixer & phpstan pre commit hook finish"
exit 0