#!/usr/bin/env bash
#/bin/sh

echo "php-cs-fixer pre commit hook start"

FILES=`git diff --cached --name-only --diff-filter=ACM | grep -e '.php$'`
if [ -z "$FILES" ]
then
    echo "No php files found in commit."
else
    echo "docker-compose run -T --rm php /usr/bin/composer php-cs-fixer-check"
    MSYS_NO_PATHCONV=1 docker-compose run -T --rm php /usr/bin/composer php-cs-fixer-check ${FILES}
    exit $?
#    git add ${FILES}
fi

echo "php-cs-fixer pre commit hook finish"
exit 0