name: Infection mutation tests
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  infection:
    runs-on: ubuntu-latest
    name: Infection
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run infection tests
        run: composer ci-infection


