name: Infection mutation tests
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]


permissions:
  contents: read


jobs:
  infection:
    runs-on: ubuntu-latest
    name: Infection
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache hash
        id: get-cache-hash
        run: |
          COMPOSER_HASH=`cat composer.json | sha256sum | head -c 40`
          DATE=`date -u "+%Y%m%d"`
          echo "hash=$COMPOSER_HASH$DATE" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-cache-hash.outputs.hash}}


      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Install infection
        run: composer install-infection-phar

      - name: Run infection tests
        run: composer ci-infection

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-cache-hash.outputs.hash}}


