name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check PHP
        run: composer check-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate --strict


      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md
  test:
    runs-on: ubuntu-latest
    name: Run tests and check them with infection
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Install dependencies
        run: composer install-infection-phar
      - name: Run phpunit tests
        run: composer phpunit
      - name: Run infection tests
        run: composer infection-auto

  style:
    runs-on: ubuntu-latest
    name: Check coding style
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run phpunit tests
        run: composer php-cs-fixer-check
