name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Install infection
        run: composer install-infection-phar

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Check PHP
        run: composer check-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  test:
    runs-on: ubuntu-latest
    name: Phpunit and infection
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Run phpunit tests
        run: composer phpunit

      - name: Run infection tests
        run: composer infection-auto

  style:
    runs-on: ubuntu-latest
    name: Check coding style
    needs: build
    steps:
      - uses: actions/checkout@v3


      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Run phpunit tests
        run: composer php-cs-fixer-check

