name: PHP Checks

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    #    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Install infection
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install-infection-phar

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Check PHP
        run: composer check-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

  test:
    runs-on: ubuntu-latest
    name: Phpunit and infection
    needs: build
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Run phpunit tests
        run: composer ci-phpunit

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: PHPUnit
          path: ./phpunit.xml
          reporter: java-junit

      - name: Run infection tests
        run: |
          composer ci-infection
          cat /tmp/infection/phpunitConfiguration.initial.infection.xml
        shell: bash

  style:
    runs-on: ubuntu-latest
    name: Check coding style
    needs: build
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Run php-cs-fixer checks
        run: |
          composer ci-php-cs-fixer 1> php-cs-fixer.xml
        shell: bash

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: php-cs-fixer
          path: ./php-cs-fixer.xml
          reporter: java-junit

  standards:
    runs-on: ubuntu-latest
    name: Check standards
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Run phpstan tests
        run: composer ci-phpstan
  insights:
    runs-on: ubuntu-latest
    name: Check insights
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpinsights
        run: composer ci-phpinsights