name: Composer checks

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Platform checks
    runs-on: ubuntu-latest
    #    runs-on: self-hosted
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Validate composer.json and composer.lock
        run: composer validate --strict --no-check-lock

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Check PHP
        run: composer check-platform-reqs


      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

