name: PHPInsights checks
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  insights:
    runs-on: ubuntu-latest
    name: Check insights
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Cache hash
        id: get-cache-hash
        run: |
          COMPOSER_HASH=`cat composer.json | sha256sum | head -c 40`
          DATE=`date -u "+%Y%m%d"`
          echo "hash=$COMPOSER_HASH$DATE" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-cache-hash.outputs.hash}}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpinsights
        run: composer ci-phpinsights

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-cache-hash.outputs.hash}}