name: PHPunit tests
on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
        shell: bash

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress

      - name: Run phpunit tests
        run: composer ci-phpunit

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: PHPUnit report
          path: ./phpunit-log.xml
          reporter: java-junit

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{steps.get-date.outputs.date}}

